import { NextRequest, NextResponse } from 'next/server'
import { randomBytes } from 'crypto'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { sendSetPasswordEmail } from '@/lib/email/send-set-password-email'
import { buildSetPasswordCallbackUrl } from '@/lib/auth/set-password-link'
import { TIMEZONE_VALUES, DEFAULT_TIMEZONE } from '@/lib/utils/timezones'

const createUserSchema = z.object({
  email:       z.string().email('Valid email required'),
  full_name:   z.string().min(1, 'Full name required'),
  // Admin accounts must be created directly in Supabase — not via this route
  role:        z.enum(['director', 'manager', 'employee']),
  phone:       z.string().optional().nullable(),
  manager_id:  z.string().uuid().optional().nullable(),
  team_id:     z.string().uuid().optional().nullable(),
  department:  z.string().optional().nullable(),
  company_ids: z.array(z.string().uuid()).min(1, 'Assign at least one company'),
  timezone:    z.enum(TIMEZONE_VALUES as [string, ...string[]]).optional(),
})

export async function POST(request: NextRequest) {
  // ── 1. Verify the caller is an admin ────────────────────────────────────────
  const supabase = await createClient()
  const { data: { user: caller } } = await supabase.auth.getUser()

  if (!caller) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: callerProfile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', caller.id)
    .single()

  if (callerProfile?.role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden: Admin only' }, { status: 403 })
  }

  // ── 2. Parse request body ───────────────────────────────────────────────────
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const parsed = createUserSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  }

  const { email, full_name, role, phone, manager_id, team_id, department, company_ids, timezone } =
    parsed.data

  // ── 3. Create auth user with a throw-away password ──────────────────────────
  // The user will immediately be emailed a "set your password" link, so the
  // temporary password is never shared and should be cryptographically random.
  const tempPassword = randomBytes(20).toString('hex')

  const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
    email,
    password: tempPassword,
    email_confirm: true, // skip the email-confirm step; they get a set-password link instead
  })

  if (authError || !authData.user) {
    return NextResponse.json(
      { error: authError?.message ?? 'Failed to create auth user' },
      { status: 500 }
    )
  }

  const newUserId = authData.user.id

  // ── 4. Upsert profile row ───────────────────────────────────────────────────
  // The auth.users INSERT trigger may have already created a minimal profile row.
  // We upsert to fill in the full details without conflicting with that trigger.
  const { data: profile, error: profileError } = await supabaseAdmin
    .from('profiles')
    .upsert({
      id:          newUserId,
      full_name,
      email,
      phone:       phone ?? null,
      role,
      manager_id:  manager_id ?? null,
      team_id:     team_id ?? null,
      department:  department ?? null,
      timezone:    timezone ?? DEFAULT_TIMEZONE,
      // employee_code is auto-generated by the DB trigger on first INSERT
    }, { onConflict: 'id' })
    .select()
    .single()

  if (profileError || !profile) {
    // Roll back the auth user so we don't orphan it
    await supabaseAdmin.auth.admin.deleteUser(newUserId)
    return NextResponse.json(
      { error: profileError?.message ?? 'Failed to create profile' },
      { status: 500 }
    )
  }

  // ── 5. Assign companies ─────────────────────────────────────────────────────
  const { error: companyError } = await supabaseAdmin
    .from('employee_companies')
    .insert(company_ids.map((company_id) => ({ employee_id: profile.id, company_id })))

  if (companyError) {
    // Non-fatal: profile exists, but company assignment failed. Log and surface.
    console.error('[createUser] company assignment failed:', companyError.message)
  }

  // ── 6. Generate a "set your password" link ──────────────────────────────────
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://wsso.vercel.app'

  const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
    type:       'recovery',
    email,
    options: {
      redirectTo: `${appUrl}/auth/callback?next=/reset-password`,
    },
  })

  if (linkError) {
    console.error('[createUser] generateLink failed:', linkError.message)
  }

  const setPasswordLink = linkData?.properties?.hashed_token
    ? buildSetPasswordCallbackUrl(linkData.properties.hashed_token)
    : linkData?.properties?.action_link ?? null

  // ── 7. Email the employee a set-password link ───────────────────────────────
  const emailResult = await sendSetPasswordEmail({
    email,
    fullName:        full_name,
    role,
    employeeCode:    profile.employee_code,
    setPasswordLink,
  })

  if (!emailResult.sent) {
    console.error('[createUser] welcome email failed:', emailResult.error)
    if (setPasswordLink) {
      console.log('[createUser] manual set-password link:', setPasswordLink)
    }
  }

  return NextResponse.json(
    {
      profile,
      email_sent:        emailResult.sent,
      email_method:      emailResult.method,
      email_error:       emailResult.error ?? null,
      set_password_link: emailResult.sent ? null : setPasswordLink,
      message: emailResult.sent
        ? 'User created. A set-password email was sent to the employee.'
        : 'User created, but the welcome email could not be sent. Check email configuration or use the set_password_link.',
    },
    { status: 201 }
  )
}
