import { NextRequest, NextResponse } from 'next/server'
import { randomBytes } from 'crypto'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'

const createUserSchema = z.object({
  email:       z.string().email('Valid email required'),
  full_name:   z.string().min(1, 'Full name required'),
  // Admin accounts must be created directly in Supabase — not via this route
  role:        z.enum(['director', 'manager', 'employee']),
  phone:       z.string().optional().nullable(),
  manager_id:  z.string().uuid().optional().nullable(),
  team_id:     z.string().uuid().optional().nullable(),
  department:  z.string().optional().nullable(),
  company_ids: z.array(z.string().uuid()).min(1, 'Assign at least one company'),
})

export async function POST(request: NextRequest) {
  // ── 1. Verify the caller is an admin ────────────────────────────────────────
  const supabase = await createClient()
  const { data: { user: caller } } = await supabase.auth.getUser()

  if (!caller) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: callerProfile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', caller.id)
    .single()

  if (callerProfile?.role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden: Admin only' }, { status: 403 })
  }

  // ── 2. Parse request body ───────────────────────────────────────────────────
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const parsed = createUserSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  }

  const { email, full_name, role, phone, manager_id, team_id, department, company_ids } =
    parsed.data

  // ── 3. Create auth user with a throw-away password ──────────────────────────
  // The user will immediately be emailed a "set your password" link, so the
  // temporary password is never shared and should be cryptographically random.
  const tempPassword = randomBytes(20).toString('hex')

  const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
    email,
    password: tempPassword,
    email_confirm: true, // skip the email-confirm step; they get a set-password link instead
  })

  if (authError || !authData.user) {
    return NextResponse.json(
      { error: authError?.message ?? 'Failed to create auth user' },
      { status: 500 }
    )
  }

  const newUserId = authData.user.id

  // ── 4. Upsert profile row ───────────────────────────────────────────────────
  // The auth.users INSERT trigger may have already created a minimal profile row.
  // We upsert to fill in the full details without conflicting with that trigger.
  const { data: profile, error: profileError } = await supabaseAdmin
    .from('profiles')
    .upsert({
      id:          newUserId,
      full_name,
      email,
      phone:       phone ?? null,
      role,
      manager_id:  manager_id ?? null,
      team_id:     team_id ?? null,
      department:  department ?? null,
      // employee_code is auto-generated by the DB trigger on first INSERT
    }, { onConflict: 'id' })
    .select()
    .single()

  if (profileError || !profile) {
    // Roll back the auth user so we don't orphan it
    await supabaseAdmin.auth.admin.deleteUser(newUserId)
    return NextResponse.json(
      { error: profileError?.message ?? 'Failed to create profile' },
      { status: 500 }
    )
  }

  // ── 5. Assign companies ─────────────────────────────────────────────────────
  const { error: companyError } = await supabaseAdmin
    .from('employee_companies')
    .insert(company_ids.map((company_id) => ({ employee_id: profile.id, company_id })))

  if (companyError) {
    // Non-fatal: profile exists, but company assignment failed. Log and surface.
    console.error('[createUser] company assignment failed:', companyError.message)
  }

  // ── 6. Generate a "set your password" link ──────────────────────────────────
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'

  const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
    type:       'recovery',
    email,
    options: {
      redirectTo: `${appUrl}/auth/callback?next=/reset-password`,
    },
  })

  if (linkError) {
    console.error('[createUser] generateLink failed:', linkError.message)
  }

  const setPasswordLink = linkData?.properties?.action_link ?? null

  // ── 7. Welcome email — placeholder (wire Resend in a later prompt) ──────────
  console.log(`
╔══════════════════════════════════════════════════════════╗
║              WELCOME EMAIL  (placeholder)                ║
╠══════════════════════════════════════════════════════════╣
║  To:            ${email.padEnd(42)}║
║  Name:          ${full_name.padEnd(42)}║
║  Role:          ${role.padEnd(42)}║
║  Employee code: ${profile.employee_code.padEnd(42)}║
╠══════════════════════════════════════════════════════════╣
║  Set your password:                                      ║
║  ${(setPasswordLink ?? '(link generation failed)').slice(0, 56).padEnd(56)}║
╚══════════════════════════════════════════════════════════╝
  `)

  return NextResponse.json(
    {
      profile,
      set_password_link: setPasswordLink,
      message: 'User created. Welcome email logged to console (Resend integration pending).',
    },
    { status: 201 }
  )
}
